#!/bin/sh

sxhkd &
bspc monitor -d I II III IV &
picom &
feh --bg-scale ~/Downloads/701802.jpg &
~/.config/polybar/launch.sh 

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#FF0000"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"








